webappfiles/auth.py
from flask_mail import Mail, Message
from . import mail
from flask import Blueprint, render_template, request, flash, redirect, url_for, session
import mysql.connector
from webappfiles import dbconnect
from werkzeug.security import generate_password_hash, check_password_hash

auth = Blueprint('auth', __name__)

@auth.route("/signup/", methods=['GET', 'POST'])
def signup():
    if request.method == 'POST':
        email = request.form['txtemail']
        first_name = request.form['txtfn']
        last_name = request.form['txtln']
        password1 = request.form['txtpwd']
        password2 = request.form['txtcpwd']

        cur, con = dbconnect.get_connection()
        sql = "select EMAIL from tblhousekeeper where EMAIL= %s"
        val = (email,)
        cur.execute(sql, val)
        rows = cur.fetchall()
        count = cur.rowcount

        if (count > 0):
            flash('User already exists.', category='error')
        if (len(email) < 5):
            flash('Email must be greater than 4 characters.', category = 'error')
        elif (len(first_name) < 3):
            flash('First name must be greater than 2 characters.', category = 'error')
        elif (password1 != password2):
            flash('Passwords don\'t match.', category = 'error')
        elif (len(password1) < 3):
            flash('Password must be at least 3 characters.', category = 'error')
        else:
            passw = generate_password_hash(password1, method='sha256')
            sql2 = "INSERT into tblhousekeeper (EMAIL, FNAME, LNAME, PASSWORD) values (%s,%s,%s,%s)"
            val2 = (email, first_name, last_name, passw)
            cur.execute(sql2, val2)
            con.commit()
            msg = str(cur.rowcount) + " record added, "

            msg1 = Message('Mohandyman store', sender ='yelenamarion@gmail.com', recipients = [email])
            msg1.body = "Welcome to mohandyman store " + first_name + "\r\n"
            msg1.body += "You are now a member and may access the website \r\n "
            msg1.body += "@ http://localhost:5000/"
            mail.send(msg1)

            flash(msg + ' account created!', category='success')
        return redirect(url_for('auth.login'))
    return render_template("signup.html")

@auth.route("/login/", methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form['txtemail']
        pwd = request.form['txtpwd']
        cur, con = dbconnect.get_connection()
        sql = "select PASSWORD, EMAIL, ID, FNAME from tblhousekeeper where EMAIL= %s"
        val = (email,)
        cur.execute(sql, val)
        rows = cur.fetchall()
        count = cur.rowcount
        for row in rows:
            passw = row[0]

        if (count > 0):
            if check_password_hash(passw, pwd):
                session['ID'] = rows[0][2]
                session['FNAME'] = rows[0][3]
                flash('Logged in successfully!', category='success')
                return redirect(url_for('views.profile'))
        else:
            flash('Incorrect password, pls try again.', category='error')
    else:
        flash('Email does not exist.', category='error')
    return render_template("login.html")

@auth.route("/loginho/", methods=['GET', 'POST'])
def loginho():
    if request.method == 'POST':
        email = request.form['txtemail']
        pwd = request.form['txtpwd']

        cur, con = dbconnect.get_connection()
        sql = "select PASSWORD, EMAIL, ID, FNAME from tblhouseowner where EMAIL= %s"
        val = (email,)
        cur.execute(sql, val)
        rows = cur.fetchall()
        count = cur.rowcount
        for row in rows:
            passw = row[0]

        if (count > 0):
            if check_password_hash(passw, pwd):
                session['ID'] = rows[0][0]
                session['FNAME'] = rows[0][1]
                flash('Logged in successfully!', category='success')
                return redirect(url_for('views.adminhome'))
        else:
            flash('Incorrect password, pls try again.', category='error')
    else:
        flash('Email does not exist.', category='error')
    return render_template("loginho.html")

@auth.route("/housekeeper/", methods=['GET', 'POST'])
def housekeeper():
    if request.method == 'POST':
        title= request.form['txttitle']
        email = request.form['txtemail']
        first_name = request.form['txtfn']
        last_name = request.form['txtln']
        password1 = request.form['txtpwd']
        password2 = request.form['txtcpwd']
        dob= request.form['txtpdate']
        postadd= request.form['txtpostaladd']
        contactnum= request.form['txtcontactnum']
        hqua= request.form['txthqua']
        filecv= request.form['filecv']
        skills= request.form['txtskills']
      

        cur, con = dbconnect.get_connection()
        sql = "select EMAIL from tblhousekeeper where EMAIL= %s"
        val = (email,)
        cur.execute(sql, val)
        rows = cur.fetchall()
        count = cur.rowcount

        if (count > 0):
            flash('User already exists.', category='error')
        if (len(email) < 5):
            flash('Email must be greater than 4 characters.', category = 'error')
        elif (len(first_name) < 3):
            flash('First name must be greater than 2 characters.', category = 'error')
        elif (password1 != password2):
            flash('Passwords don\'t match.', category = 'error')
        elif (len(password1) < 3):
            flash('Password must be at least 3 characters.', category = 'error')
        else:
            passw = generate_password_hash(password1, method='sha256')
            sql2 = "INSERT into tblhousekeeper (TITLE, LNAME, FNAME, EMAIL, PASSWORD, DOB, POSTAL_ADDRESS, CONTACT_NUMBER, HIGHEST_QUALIFICATION,  CV_UPLOAD, SKILL_ID) values (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)"
            val2 = (title, first_name, last_name, email, passw, dob, postadd, contactnum, hqua, filecv, skills)
            cur.execute(sql2, val2)
            con.commit()
            msg = str(cur.rowcount) + " record added, "

            msg1 = Message('Mohandyman store', sender ='yelenamarion@gmail.com', recipients = [email])
            msg1.body = "Welcome to mohandyman store " + first_name + "\r\n"
            msg1.body += "You are now a member and may access the website \r\n "
            msg1.body += "@ http://localhost:5000/"
            mail.send(msg1)

            flash(msg + ' account created!', category='success')
        return redirect(url_for('auth.login'))
    return render_template("housekeeper.html")


@auth.route("/houseowner/", methods=['GET', 'POST'])
def houseowner():
    if request.method == 'POST':
        email = request.form['txtemail']
        first_name = request.form['txtfn']
        last_name = request.form['txtln']
        password1 = request.form['txtpwd']
        password2 = request.form['txtcpwd']
        postadd= request.form['txtpostaladd']
        district= request.form["txtdistrict"]

        cur, con = dbconnect.get_connection()
        sql = "select EMAIL from tblhouseowner where EMAIL= %s"
        val = (email,)
        cur.execute(sql, val)
        rows = cur.fetchall()
        count = cur.rowcount

        if (count > 0):
            flash('User already exists.', category='error')
        if (len(email) < 5):
            flash('Email must be greater than 4 characters.', category = 'error')
        elif (len(first_name) < 3):
            flash('First name must be greater than 2 characters.', category = 'error')
        elif (password1 != password2):
            flash('Passwords don\'t match.', category = 'error')
        elif (len(password1) < 3):
            flash('Password must be at least 3 characters.', category = 'error')
        else:
            passw = generate_password_hash(password1, method='sha256')
            sql2 = "INSERT into tblhouseowner (LNAME, FNAME, EMAIL, PASSWORD, POSTAL_ADDRESS, DISTRICT ) values (%s,%s,%s,%s,%s,%s)"
            val2 = (first_name, last_name, email, passw, postadd, district )
            cur.execute(sql2, val2)
            con.commit()
            msg = str(cur.rowcount) + " record added, "

            msg1 = Message('Mohandyman store', sender ='yelenamarion@gmail.com', recipients = [email])
            msg1.body = "Welcome to mohandyman store " + first_name + "\r\n"
            msg1.body += "You are now a member and may access the website \r\n "
            msg1.body += "@ http://localhost:5000/"
            mail.send(msg1)

            flash(msg + ' account created!', category='success')
        return redirect(url_for('auth.loginho'))
    return render_template("houseowner.html")


@auth.route('/logout/')
def logout():
    session.pop('ID')
    return redirect('/')

webappfiles/views.py
from turtle import title
from flask import Blueprint, render_template, request, session, redirect, flash

import mysql.connector
from webappfiles import dbconnect

from datetime import datetime
import os

views = Blueprint('views', __name__)

cur, con = dbconnect.get_connection()
#referring to the default page via the “/” route
@views.route("/")
def home():
    return render_template("index.html")

@views.route("/houseowner/")
def houseowner():
    return render_template("houseowner.html")



@views.route("/login/")
def login():
    return render_template("login.html")

@views.route("/loginho/")
def loginho():
    return render_template("loginho.html")

@views.route("/signup/")
def signup():
    return render_template("signup.html")

@views.route("/viewjobs/")
def viewjobs():
    cur.execute("SELECT * FROM tbljob")
    rows = cur.fetchall()
    return render_template("viewjobs.html", rows = rows)

@views.route("/adminhome/")
def adminhome():
    return render_template("adminhome.html")



@views.route("/addjob/")
def add_job():

    cur.execute("select* from tbldistrict")
    rows1=cur.fetchall()
    return render_template("addjob.html",rows1=rows1)




@views.route("/savedetails", methods = ["POST"])
def saveDetails():
    msg = "msg"
    if request.method == "POST":
        try:
            # add codes to retrieve the form values
            title = request.form["txttitle"]
            salary = request.form["txtsal"]
            ref = request.form["txtref"]
            desr = request.form["txtdesc"]
            dt = request.form["txtcdate"]
            ho= request.form["txtho"]
            f = request.files["filecover"]
            f.save(os.path.join("./webappfiles/static/images" , f.filename))
            full_filename = os.path.join("/static/images" , f.filename)
            sql = "INSERT into tbljob (JOB_TITLE, SALARY, JOB_REFERENCE, JOD_DESCRIPTION, CLOSING_DATE, HOUSEOWNER, JOB_COVER) values (%s,%s,%s,%s,%s,%s,%s)"
            # add the form variables for each column
            val = (title,salary,ref,desr,dt, ho,full_filename)
            cur.execute(sql, val)
            con.commit()
            msg = str(cur.rowcount) + " job added"
        except Exception as e:
            con.rollback()
            msg = "Job cannot be added " + str(e)
        finally:
            #pass the msg variable to the return statement
            return render_template("addjob.html",msg=msg, title=title)
            con.close()


@views.route("/joblisting/")
def job_listing():
    cur, con = dbconnect.get_connection()
    cur.execute("SELECT * FROM tbljob")
    rows = cur.fetchall()
    return render_template('joblisting.html', rows=rows)

@views.route("/searchjob/")
def search_job():
    return render_template("search.html")

@views.route("/searchjb/", methods = ["GET"])
def searchjob():
    #retrieve the querystring txtlang from the URL
    title = request.args.get("txtjob")
    try:
        sql = "select * from tbljob  WHERE JOB_TITLE = %s "
        val = (title,)
        cur.execute(sql, val)
        rows = cur.fetchall()
        msg = str(cur.rowcount) + " record found!"
    except:
        msg = "There was an issue while searching!"
    finally:
        return render_template("search.html", rows=rows,msg = msg, title=title) 


@views.route("/updatejob/")
def update_job():
    return render_template("updatejob.html")


@views.route("/updaterecord/", methods = ["POST"])
def updaterecord():
    #retrieve the form values
    salary = request.form["txtsalary"]
    title = request.form["txttitle"]
    try:
        sql = "UPDATE tbljob SET SALARY = %s where JOB_TITLE = %s"
        val = (salary, title)
        cur.execute(sql, val)
        con.commit()
        msg = str(cur.rowcount) + " record successfully updated"
    except:
        msg = "Cannot be updated"
    finally:
        return render_template("updatejob.html", msg = msg)



@views.route("/profile/")
def profile():
    if 'ID' in session:
        cur, con = dbconnect.get_connection()
        sql = "SELECT * FROM tblhousekeeper where ID = %s"
        val = (session.get('ID'),)
        cur.execute(sql, val)
        rows = cur.fetchall()
        return render_template('profile.html', rows=rows)
    else:
        return redirect('/')


@views.route("/profileho/")
def profileho():
    if 'ID' in session:
        cur, con = dbconnect.get_connection()
        sql = "SELECT * FROM tblhouseowner where ID = %s"
        val = (session.get('ID'),)
        cur.execute(sql, val)
        rows = cur.fetchall()
        return render_template('profileho.html', rows=rows)
    else:
        return redirect('/')

@views.route("/updateprofile/", methods=["GET", "POST"])
def update_profile():
    if request.method == "POST":
        email = request.form['txtemail']
        first_name = request.form['txtfn']
        last_name = request.form['txtln']
        contactnum = request.form['txtcontactnum']
        try:
            cur, con = dbconnect.get_connection()
            sql = "UPDATE tblhousekeeper SET EMAIL = %s, FNAME = %s, LNAME = %s , CONTACT_NUMBER = %s where ID = %s"
            val = (email, first_name, last_name, contactnum, session['ID'])
            cur.execute(sql, val)
            con.commit()
            msg = str(cur.rowcount) + " record successfully updated"
            flash(msg, category='success')
        except:
            msg = "Cannot be updated"
            flash(msg, category='error')
        finally:
            return redirect('/profile/')
    else:
        return redirect('/login/')


@views.route("/updateprofileho/", methods=["GET", "POST"])
def update_profileho():
    if request.method == "POST":
        email = request.form['txtemail']
        first_name = request.form['txtfn']
        last_name = request.form['txtln']
     
        try:
            cur, con = dbconnect.get_connection()
            sql = "UPDATE tblhouseowner SET EMAIL = %s, FNAME = %s, LNAME = %s  where ID = %s"
            val = (email, first_name, last_name, session.get('ID'),)
            cur.execute(sql, val)
            con.commit()
            msg = str(cur.rowcount) + " record successfully updated"
            flash(msg, category='success')
        except:
            msg = "Cannot be updated"
            flash(msg, category='error')
        finally:
            return redirect('/profileho/')
    else:
        return redirect('/adminhome/')


@views.route("/housekeeper/")
def housekeeper():
    cur, con = dbconnect.get_connection()
    cur.execute("SELECT * FROM tblskills")
    rows = cur.fetchall()
    return render_template('housekeeper.html', rows=rows)



@views.route("/application/")
def application():
    cur.execute("SELECT * FROM tbljob jb INNER JOIN tblhouseowner ho on (jb.HOUSEOWNER=ho.ID)")
    rows1 = cur.fetchall()
    return render_template("application.html", rows1 = rows1)

@views.route("/submit_app/", methods=['GET', 'POST'])
def submit_app():
    if request.method == 'POST':
        job = request.form['txtjob']
        date = request.form['txtdate']
        sql = "INSERT into tblapplication (DATE_OF_APPLICATION, JOB, HOUSEKEEPER) values (%s,%s,%s)"
        val = (date, job, session.get('ID'))
        cur.execute(sql, val)
        con.commit()
    return render_template("application.html")

@views.route("/searchskill/")
def searchskill():
    return render_template("searchskill.html")

@views.route("/searchsk/", methods = ["GET"])
def searchsk():
#retrieve the querystring txtlang from the URL
    title = request.args.get("txtsk")
    try:
        sql = "select * from tblhousekeeper hk INNER JOIN tblskills sk ON (hk.ID=sk.ID) where SKILL_TYPE = %s"
        val = (title,)
        cur.execute(sql, val)
        rows = cur.fetchall()
        msg = str(cur.rowcount) + " record found!"
    except:
        msg = "There was an issue while searching!"
    finally:
        return render_template("searchskill.html", msg = msg, rows=rows, title = title)

webappfiles/templates/addjob.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<title>Post a job</title>
		<link
			href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
			rel="stylesheet"
			integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
			crossorigin="anonymous"
		/>
		<script
			src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
			integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
			crossorigin="anonymous"
		></script>
		<link
			rel="stylesheet"
			href="{{ url_for('static', filename='css/styles.css') }}"
		/>
		<link rel="shortcut icon" href="../icon/favicon.ico" type="image/x-icon" />
		<link rel="icon" href="../icon/favicon.ico" type="image/x-icon" />
		<link
			rel="stylesheet"
			href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css"
		/>
	</head>
	<body class="bg_color">
		{% extends "basehouseowner.html" %} {% block content %} {{msg}} {{title}}
	
		<div class="container row my-5">
			<div >
			  <form class="row" action="/savedetails" method="post" enctype="multipart/form-data" >
				<h2 class="mt-3">Post a job</h2>
			
				<div class="mb-3">
				  <label for="txttitle" class="form-label">Title</label>
				  <input
					type="text"
					class="form-control"
					name="txttitle"
					id="txttitle"
				  />
				</div>
				<div class="mb-3">
				  <label for="txtdesc" class="form-label">Job Description</label>
				  <textarea
					type="text"
					class="form-control"
					id="txtdesc"
					name="txtdesc"></textarea>
				</div>
				<div class="mb-3">
				  <label for="txtref" class="form-label">Job Reference</label>
				  <input
	  
					type="text"
					class="form-control"
					id="txtref"
					name="txtref"
				  />
				</div>
				<div class="mb-3">
				  <label for="txtsal" class="form-label">Salary</label>
				  <input
	  
					type="text"
					class="form-control"
					id="txtsal"
					name="txtsal"
				  />
				<div class="mb-3">
				  <label for="txtcdate" class="form-label">Closing Date</label>
				  <input
					autocomplete="off"
					type="date"
					class="form-control"
					id="txtcdate"
					name="txtcdate"
				/>

				</div>
				<div class="mb-3">
					<label for="txtho" class="form-label">Houseowner</label>
					<input
					  autocomplete="off"
					  type="text"
					  class="form-control"
					  id="txtho"
					  name="txtho"
				  />
  
				  </div>
				  <div class="mb-3">
					<label for="filecover" class="form-label">Upload Job Cover</label>
					<input
						class="form-control form-control-lg"
						id="filecover"
						name="filecover"
						type="file"
					/>
				</div>
				<button type="submit" class="col-6 btn btn-primary mx-auto">
				  Add Job
				</button>
			  </form>
			</div>
			
		  </div>
				
		{% endblock %}
	</body>
</html>

webappfiles/templates/basehouseowner.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/scroll.css') }}">
  <title>Base template for houseowner</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css"
  rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor"
  crossorigin="anonymous">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/baseadmin.css') }}">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/main.min.css') }}">  
  <link rel="stylesheet" href="{{ url_for('static', filename='css/main.min.css.map') }}">
  <link rel="icon" type="image/x-icon" href="{{url_for('static', filename='images/logo.jpg')}}>
    <script src="https://kit.fontawesome.com/f477c74259.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.3/font/bootstrap-icons.css">
</head>

<!--Responsive nav in the header inside the body tag-->

<header class="row">

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="{{url_for('views.home')}}"
                >Mohandyman Portal</a
            >

            <button
                class="navbar-toggler"
                type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation"
            >
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item">
                        <a
                            class="nav-link active"
                            aria-current="page"
                            href="{{url_for('views.adminhome')}}"
                            >Home</a
                        >
                    </li>

                    <li class="nav-item dropdown">
                        <a
                            class="nav-link active dropdown-toggle"
                            href="#"
                            id="navbarDropdown"
                            role="button"
                            data-bs-toggle="dropdown"
                            aria-expanded="false"
                        >
                            Houseowner
                        </a>

                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            {% if 'ID' not in session %}
                            <li>
                                <a class="dropdown-item" href="{{url_for('views.houseowner')}}"
                                    >Sign Up</a
                                >
                            </li>
                            <li>
                                <a class="dropdown-item" href="{{url_for('views.loginho')}}"
                                    >Login</a
                                >
                                {% else %}
                                <a
									class="btn btn-dark text-white mx-1"
									href="{{url_for('auth.logout')}}"
									>Logout</a
								>
								<br />
								<br />
								<a
									class="btn btn-dark mx-1"
									href="{{url_for('views.profileho')}}"
									>{{session["FNAME"]}}</a
								>
								{% endif %}
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>


</header>

    <main>

      <div class="container-fluid ">
          <div class="row">
              <nav class="col-md-2  bg-dark flex-column min-vh-100">
              <div class="accordion mt-4" id="accordionExample">
                <div class="accordion-item">
                    <h2 class="accordion-header" id="headingdashboard">
        <a class="nav-link" href="#"><strong>Dashboard</strong></a>
                    </h2>
                </div>
        <div class="accordion-item">
        <h2 class="accordion-header" id="headingOne">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
        data-bs-target="#collapseOne" aria-expanded="false" aria-controls="collapseOne"> Manage Jobs
        </button>
        </h2>
      
        <div id="collapseOne" class="accordion-collapse collapse" aria-labelledby="headingOne" 
        data-bs-parent="#accordionExample">
          <div class="accordion-body">
        <a class="nav-link" href="/addjob"><strong>Add Job</strong></a>
        <a class="nav-link" href="/viewjobs"><strong>View jobs posted</strong></a>
        <a class="nav-link" href="/searchjob"><strong>Search Job</strong></a>
        <a class="nav-link" href="/updatejob"><strong>Update Job</strong></a>
        <a class="nav-link" href="/searchskill"><strong>Search by Skill</strong></a>
          </div>
        </div>
        </div>
              <div class="accordion-item">
        <h2 class="accordion-header" id="headingTwo">
        <button class="accordion-button collapsed" type="button"
        data-bs-toggle="collapse"
        data-bs-target="#collapseTwo" aria-expanded="false"
        aria-controls="collapseTwo"> Board 2
        </button>

      </h2>
<div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo"
      data-bs-parent="#accordionExample">
          <div class="accordion-body">
      <a class="nav-link" href="/searchh_keeper"><strong>Housekeeper</strong></a>
      <a class="nav-link" href="#"><strong>Link 2</strong></a>
          </div>
</div>
                </div>

<div class="accordion-item">
      <h2 class="accordion-header" id="headingThree">
      <button class="accordion-button collapsed" type="button"
      data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false"
      aria-controls="collapseThree"> board 3
      </button>
      </h2>
      
        <div id="collapseThree" class="accordion-collapse collapse" arialabelledby=" headingThree"
      data-bs-parent="#accordionExample">
      <div class="accordion-body">
      <a class="nav-link" href="#"><strong>Link 3</strong></a>
      <a class="nav-link" href="#"><strong>Link 4</strong></a>
      </div>
        </div>
</div>
      </div>
      </nav>
      <main class="col-md-7 offset-md-1 py-5">
        {% block content %}
        {% with messages = get_flashed_messages(with_categories=true) %} 
                {% if messages %} 
                        {% for category, message in messages %} 
                                {% if category == '' %}
                                        <div class="alert alert-danger alert-dismissible fade show"
                                        role="alert">
                                        {{ message }}
                                        <button type="button" class="btn-close" data-bs-dismiss="alert">
                                        </button>
                                        </div>
                                {% else %}
                                        <div class="alert alert-success alert-dismissible fade show"
                                        role="alert">
                                        {{ message }}
                                        <button type="button" class="btn-close" data-bs-dismiss="alert">
                                        </button>
                                        </div>
                                {% endif %} 
                        {% endfor %} 
                {% endif %} 
        {% endwith %}

        {% endblock %}
      </main>
      </div>
      </div>
    </main>

<script
      type="text/javascript"
      src="{{url_for('static', filename='js/jquery-3.6.0.js')}}"
    ></script>
    <script
      type="text/javascript"
      src="{{url_for('static', filename='js/bootstrap.min.js')}}"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
      integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
      integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF"
      crossorigin="anonymous"
    ></script>


</body>
</html>

webappfiles/templates/joblisting.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<title>Job listing</title>
	</head>
	<body>
		{% extends "basehousekeeper.html" %} {% block content %}
		<h1 class="text-center .text-dark">Jobs List</h1>
		<hr />
		<div class="row text-center">
			{% for row in rows %}
			<div class="col-md-4 pt-5">
				<div class="card mx-auto" style="width: 18rem">
					<img src="{{row.6}}" class="card-img-top" />
					<div class="card-body">
						<h5 class="card-title text-success">{{row.1}}</h5>
						<p class="card-text"><b>Salary</b> Rs.{{row.2}}</p>
						<p class="card-text"><b>Job Reference</b>{{row.3}}</p>
						<p class="card-text"><b>Job Reference</b>{{row.4}}</p>
						<a href="{{url_for('views.application')}}" class="btn btn-primary"
							>Apply</a
						>
					</div>
				</div>
			</div>
			{% endfor %}
		</div>
		{% endblock %}
	</body>
</html>